tabla_conmebol = [
    
 "2022",    "Recopa Conmebol"     ,"Palmeiras"	
,"2021",    "Recopa Conmebol"     ,"Def y Justicia"		
,"2020",    "Recopa Conmebol"     ,"Flamengo"	
,"2019",    "Recopa Conmebol"     ,"River Plate"	
,"2018",    "Recopa Conmebol"     ,"Gremio"	
,"2017",    "Recopa Conmebol"     ,"Atl. Nacional"	
,"2016",    "Recopa Conmebol"     ,"River Plate"	
,"2015",    "Recopa Conmebol"     ,"River Plate"	
,"2014",    "Recopa Conmebol"     ,"Atl. Mineiro"	
,"2013",    "Recopa Conmebol"     ,"Corinthians"	
,"2012",    "Recopa Conmebol"     ,"Santos"	
,"2011",    "Recopa Conmebol"     ,"Internacional"	
,"2010",    "Recopa Conmebol"     ,"Liga Quito"	
,"2009",    "Recopa Conmebol"     ,"Liga Quito"	
,"2008",    "Recopa Conmebol"     ,"Boca Juniors"	
,"2007",    "Recopa Conmebol"     ,"Internacional"	
,"2006",    "Recopa Conmebol"     ,"Boca Juniors"	
,"2005",    "Recopa Conmebol"     ,"Boca Juniors"	
,"2004",    "Recopa Conmebol"     ,"Cienciano"	
,"2003",    "Recopa Conmebol"     ,"Olimpia"	
,"1998",    "Recopa Conmebol"     ,"Cruzeiro"	
,"1997",    "Recopa Conmebol"     ,"Vélez Sarsfield"	
,"1996",    "Recopa Conmebol"     ,"Gremio"	
,"1995",    "Recopa Conmebol"     ,"Independiente"		
,"1994",    "Recopa Conmebol"     ,"Sao Paulo"		
,"1993",    "Recopa Conmebol"     ,"Sao Paulo"		
,"1992",    "Recopa Conmebol"     ,"Colo Colo"		
,"1991",    "Recopa Conmebol"     ,"Olimpia"		
,"1990",    "Recopa Conmebol"     ,"Boca Juniors"	
,"1989",    "Recopa Conmebol"     ,"Nacional"    


,"2019","Suruga Bank","Paranaense"	    	
,"2018","Suruga Bank","Independiente"	
,"2017","Suruga Bank","Urawa RD"	    
,"2016","Suruga Bank","Ind. Santa Fe"		
,"2015","Suruga Bank","River Plate"	    	
,"2014","Suruga Bank","Kashiwa Reysol"		
,"2013","Suruga Bank","Kashima A."	
,"2012","Suruga Bank","Kashima A."	
,"2011","Suruga Bank","Jubilo Iwata"	
,"2010","Suruga Bank","FC Tokyo"	
,"2009","Suruga Bank","Internacional"		
,"2008","Suruga Bank","Arsenal"



,"2022","Libertadores de América",	"Flamengo"	        
,"2021","Libertadores de América",	"Palmeiras"	        
,"2020","Libertadores de América",	"Palmeiras"	        
,"2019","Libertadores de América",	"Flamengo"	        
,"2018","Libertadores de América",	"River Plate"	        
,"2017","Libertadores de América",	"Gremio"            
,"2016","Libertadores de América",	"Atl. Nacional"	    
,"2015","Libertadores de América",	"River Plate"	        
,"2014","Libertadores de América",	"San Lorenzo de Almagro"	        
,"2013","Libertadores de América",	"Atl. Mineiro"	    
,"2012","Libertadores de América",	"Corinthians"	        
,"2011","Libertadores de América",	"Santos"	            
,"2010","Libertadores de América",	"Internacional"	    
,"2009","Libertadores de América",	"Estudiantes (LP)"	
,"2008","Libertadores de América",	"Liga Quito"	        
,"2007","Libertadores de América",	"Boca Juniors"	    
,"2006","Libertadores de América",	"Internacional"	    
,"2005","Libertadores de América",	"Sao Paulo"	        
,"2004","Libertadores de América",	"Once Caldas"	        
,"2003","Libertadores de América",	"Boca Juniors"	    
,"2002","Libertadores de América",	"Olimpia"	            
,"2001","Libertadores de América",	"Boca Juniors"	    
,"2000","Libertadores de América",	"Boca Juniors"	    
,"1999","Libertadores de América",	"Palmeiras"	        
,"1998","Libertadores de América",	"Vasco da Gama"	    
,"1997","Libertadores de América",	"Cruzeiro"	        
,"1996","Libertadores de América",	"River Plate"	        
,"1995","Libertadores de América",	"Gremio"	            
,"1994","Libertadores de América",	"Vélez Sarsfield"	            
,"1993","Libertadores de América",	"Sao Paulo"	        
,"1992","Libertadores de América",	"Sao Paulo"	        
,"1991","Libertadores de América",	"Colo Colo"	        
,"1990","Libertadores de América",	"Olimpia"	            
,"1989","Libertadores de América",	"Atl. Nacional"	    
,"1988","Libertadores de América",	"Nacional"	        
,"1987","Libertadores de América",	"Peñarol"	            
,"1986","Libertadores de América",	"River Plate"	        
,"1985","Libertadores de América",	"Argentinos"	        
,"1984","Libertadores de América",	"Independiente"	    
,"1983","Libertadores de América",	"Gremio"            
,"1982","Libertadores de América",	"Peñarol"	            
,"1981","Libertadores de América",	"Flamengo"	        
,"1980","Libertadores de América",	"Nacional"	        
,"1979","Libertadores de América",	"Olimpia"	            
,"1978","Libertadores de América",	"Boca Juniors"	    
,"1977","Libertadores de América",	"Boca Juniors"	    
,"1976","Libertadores de América",	"Cruzeiro"	        
,"1975","Libertadores de América",	"Independiente"	    
,"1974","Libertadores de América",	"Independiente"	    
,"1973","Libertadores de América",	"Independiente"	    
,"1972","Libertadores de América",	"Independiente"	    
,"1971","Libertadores de América",	"Nacional"	        
,"1970","Libertadores de América",	"Estudiantes (LP)"	
,"1969","Libertadores de América",	"Estudiantes (LP)"	
,"1968","Libertadores de América",	"Estudiantes (LP)"	
,"1967","Libertadores de América",	"Racing Club"	        
,"1966","Libertadores de América",	"Peñarol"	            
,"1965","Libertadores de América",	"Independiente"	    
,"1964","Libertadores de América",	"Independiente"	    
,"1963","Libertadores de América",	"Santos"	            
,"1962","Libertadores de América",	"Santos"	            
,"1961","Libertadores de América",	"Peñarol"	            
,"1960","Libertadores de América",	"Peñarol"



,"1997","Supercopa",	"River Plate"	
,"1996","Supercopa",	"Vélez Sarsfield"
,"1995","Supercopa",	"Independiente"
,"1994","Supercopa",	"Independiente"
,"1993","Supercopa",	"Sao Paulo"
,"1992","Supercopa",	"Cruzeiro"
,"1991","Supercopa",	"Cruzeiro"
,"1990","Supercopa",	"Olimpia"	
,"1989","Supercopa",	"Boca Juniors"
,"1988","Supercopa",	"Racing Club"


,"1998","Interamericana","DC United"
,"1997","Interamericana","Atl. Nacional"	
,"1996","Interamericana","Vélez Sarsfield"
,"1994","Interamericana","U. Catolica"
,"1992","Interamericana","Colo Colo"
,"1991","Interamericana","America"
,"1990","Interamericana","Atl. Nacional"
,"1989","Interamericana","Nacional"
,"1987","Interamericana","River Plate"
,"1986","Interamericana","Argentinos"
,"1981","Interamericana","Pumas UNAM"
,"1979","Interamericana","Olimpia"
,"1978","Interamericana","America"
,"1976","Interamericana","Independiente"
,"1974","Interamericana","Independiente"
,"1973","Interamericana","Independiente"
,"1972","Interamericana","Nacional"
,"1969","Interamericana","Estudiantes (LP)"


,"2001","Mercosur",	"San Lorenzo de Almagro"
,"2000","Mercosur",	"Vasco da Gama"
,"1999","Mercosur",	"Flamengo"
,"1998","Mercosur",	"Palmeiras"

,"1999","Copa Conmebol",	"Talleres (C)"
,"1998","Copa Conmebol",	"Santos"
,"1997","Copa Conmebol",	"Atl. Mineiro"
,"1996","Copa Conmebol",	"Lanus"
,"1995","Copa Conmebol",	"Rosario Central"
,"1994","Copa Conmebol",	"Sao Paulo"
,"1993","Copa Conmebol",	"Botafogo"
,"1992","Copa Conmebol",	"Atl. Mineiro"

,"1996","Nicolas Leoz",	"Flamengo"
,"1995","Nicolas Leoz",	"Cruzeiro"
,"1993","Nicolas Leoz",	"Boca Juniors"

,"1994","Copa Master",	"Cruzeiro"
,"1992","Copa Master",	"Boca Juniors"


,"2022","Sudamericana",	"Ind. del Valle"
,"2021","Sudamericana",	"Paranaense"
,"2020","Sudamericana",	"Def y Justicia"
,"2019","Sudamericana",	"Ind. del Valle"
,"2018","Sudamericana",	"Paranaense"
,"2017","Sudamericana",	"Independiente"
,"2016","Sudamericana",	"Chapecoense"
,"2015","Sudamericana",	"Ind. Santa Fe"
,"2014","Sudamericana",	"River Plate"
,"2013","Sudamericana",	"Lanus"
,"2012","Sudamericana",	"Sao Paulo"
,"2011","Sudamericana",	"Univ. de Chile"
,"2010","Sudamericana",	"Independiente"
,"2009","Sudamericana",	"Liga Quito"
,"2008","Sudamericana",	"Internacional"
,"2007","Sudamericana",	"Arsenal"
,"2006","Sudamericana",	"Pachuca"
,"2005","Sudamericana",	"Boca Juniors"
,"2004","Sudamericana",	"Boca Juniors"
,"2003","Sudamericana",	"Cienciano"
,"2002","Sudamericana",	"San Lorenzo de Almagro"            
]