tabla_copas_nac = [
"1900", "Tie Cup Competition 1900",           	                             "Amateur","Belgrano Athletic"
,"1901","Tie Cup Competition 1901",                                          "Amateur","Alumni"
,"1902","Tie Cup Competition 1902",                                          "Amateur","Rosario Athletic"
,"1903","Tie Cup Competition 1903",                                          "Amateur","Alumni"
,"1904","Tie Cup Competition 1904",                                          "Amateur","Rosario Athletic"
,"1905","Tie Cup Competition 1905",                                          "Amateur","Rosario Athletic"
,"1905","Copa de Honor MCBA 1905",                                           "Amateur","Alumni"
,"1906","Tie Cup Competition 1906",                                          "Amateur","Alumni"
,"1906","Copa de Honor MCBA 1906",                                           "Amateur","Alumni"
,"1907","Copa Competencia Jockey Club 1907",                                 "Amateur","Alumni"
,"1907","Copa de Honor MCBA 1907",	                                         "Amateur","Belgrano Athletic"
,"1908","Copa Competencia Jockey Club 1908",                                 "Amateur","Alumni"
,"1908","Copa de Honor MCBA 1908",	                                         "Amateur","Quilmes Athletic Club"
,"1909","Copa Competencia Jockey Club 1909",                                 "Amateur","Alumni"
,"1909","Copa de Honor MCBA 1909",	                                         "Amateur","Club Atlético San Isidro"
,"1910","Copa Competencia Jockey Club 1910",                                 "Amateur","Estudiantes de Buenos Aires"
,"1911","Copa Competencia Jockey Club 1911",	                             "Amateur","Club Atlético San Isidro"
,"1911","Copa de Honor MCBA 1911",	                                         "Amateur","Newells Old Boys"
,"1912","Copa de Honor MCBA 1912",	                                         "Amateur","Racing Club"
,"1912","Copa Competencia Jockey Club 1912",	                             "Amateur","Club Atlético San Isidro"
,"1913","Copa Competencia Jockey Club 1913",	                             "Amateur","Club Atlético San Isidro"
,"1913","Copa de Honor MCBA 1913",	                                         "Amateur","Racing Club"
,"1913","Copa Competencia La Nación 1913",	                                 "Amateur","Rosario Central"
,"1913","Copa Carlos Ibarguren 1913",	                                     "Amateur","Racing Club"
,"1914","Copa Competencia Jockey Club 1914",	                             "Amateur","River Plate"
,"1914","Copa Carlos Ibarguren 1914",	                                     "Amateur","Racing Club"
,"1914","Copa Competencia La Nación 1914",	                                 "Amateur","Independiente"
,"1915","Copa Competencia Jockey Club 1915",	                             "Amateur","Porteño"
,"1915","Copa Carlos Ibarguren 1915",	                                     "Amateur","Rosario Central"
,"1915","Copa de Honor MCBA 1915",	                                         "Amateur","Racing Club"
,"1916","Copa de Honor MCBA 1916",	                                         "Amateur","Rosario Central"
,"1916","Copa Competencia Jockey Club 1916",                                 "Amateur","Rosario Central"
,"1916","Copa Carlos Ibarguren 1916",	                                     "Amateur","Racing Club"
,"1917","Copa Competencia Jockey Club 1917",                                 "Amateur","Independiente"
,"1917","Copa de Honor MCBA 1917",	                                         "Amateur","Racing Club"
,"1917","Copa Carlos Ibarguren 1917",	                                     "Amateur","Racing Club"
,"1918","Copa Competencia Jockey Club 1918",                                 "Amateur","Porteño"
,"1918","Copa de Honor MCBA 1918",	                                         "Amateur","Independiente"
,"1918","Copa Carlos Ibarguren 1918",	                                     "Amateur","Racing Club"
,"1919","Copa Competencia Jockey Club 1919",                                 "Amateur","Boca Juniors"
,"1919","Copa Carlos Ibarguren 1919",	                                     "Amateur","Boca Juniors"
,"1920","Copa de Honor MCBA 1920",	                                         "Amateur","Banfield"
,"1920","Copa Estímulo 1920",	                                             "Amateur","Huracán"
,"1920","Copa Competencia Asociación Amateurs 1920",                         "Amateur","Rosario Central"
,"1920","Copa Carlos Ibarguren 1920",	                                     "Amateur","Tiro Federal de Rosario"
,"1921","Copa Carlos Ibarguren 1921",	                                     "Amateur","Newells Old Boys"
,"1921","Copa Competencia Jockey Club 1921",	                             "Amateur","Sportivo Barracas"
,"1922","Copa Carlos Ibarguren 1922",                                        "Amateur","Huracán"
,"1923","Copa Carlos Ibarguren 1923",                                        "Amateur","Boca Juniors"
,"1924","Copa Carlos Ibarguren 1924",                                        "Amateur","Boca Juniors"
,"1924","Copa Competencia Asociación Amateurs 1924",	                     "Amateur","Independiente"
,"1925","Copa Carlos Ibarguren 1925",	                                     "Amateur","Huracán"
,"1925","Copa Competencia Jockey Club 1925",	                             "Amateur","Boca Juniors"
,"1925","Copa Competencia Asociación Amateurs 1925",	                     "Amateur","Independiente"
,"1926","Copa Competencia Asociación Amateurs 1926",	                     "Amateur","Independiente"
,"1926","Copa Estímulo 1926",	                                             "Amateur","Boca Juniors"
,"1931","Copa Competencia 1931",	                                         "Amateur","Sportivo Balcarce"
,"1933","Copa Competencia Jockey Club 1933",	                             "Amateur","Nueva Chicago"
,"1932","Copa Competencia Liga Argentina 1932",	                             "Profesional","River Plate"
,"1932","Copa de Honor Beccar Varela 1932",	                                 "Profesional","Racing Club"
,"1933","Copa Competencia 1933",	                                         "Profesional","Racing Club"
,"1933","Copa de Honor Beccar Varela 1933",	                                 "Profesional","Central Córdoba (R)"
,"1937","Copa Carlos Ibarguren 1937",                                        "Profesional","River Plate"
,"1938","Copa Carlos Ibarguren 1938",                                        "Profesional","Independiente"
,"1939","Copa Carlos Ibarguren 1939",                                        "Profesional","Independiente"
,"1939","Copa Adrián Escobar 1939",                                          "Profesional","Independiente"
,"1940","Copa Carlos Ibarguren 1940",                                        "Profesional","Boca Juniors"
,"1941","Copa Adrián Escobar 1941",                                          "Profesional","River Plate"
,"1941","Copa Carlos Ibarguren 1941",                                        "Profesional","River Plate"
,"1942","Copa Carlos Ibarguren 1942",                                        "Profesional","River Plate"
,"1942","Copa Adrián Escobar 1942",                                          "Profesional","Huracán"
,"1943","Copa Adrián Escobar 1943",                                          "Profesional","Huracán"
,"1943","Copa General de División Pedro Pablo Ramírez 1943",	             "Profesional","San Lorenzo de Almagro"
,"1944","Copa Carlos Ibarguren 1944",	                                     "Profesional","Boca Juniors"
,"1944","Copa General de División Pedro Pablo Ramírez 1944",	             "Profesional","San Martín de Tucumán"
,"1944","Copa Competencia-Británica 1944",	                                 "Profesional","Huracán"
,"1944","Copa Adrián Escobar 1944",	                                         "Profesional","Estudiantes de La Plata"
,"1945","Copa General de División Pedro Pablo Ramírez 1945",	             "Profesional","Estudiantes de La Plata"
,"1945","Copa Competencia-Británica 1945",	                                 "Profesional","Racing Club"
,"1946","Copa Competencia George VI 1946",	                                 "Profesional","Boca Juniors"
,"1949","Copa Adrián Escobar 1949",	                                         "Profesional","Newells Old Boys"
,"1952","Copa Carlos Ibarguren 1952",	                                     "Profesional","River Plate"
,"1958","Copa Suecia 1958",	                                                 "Profesional","Atlanta"
,"1969","Copa Argentina 1969",	                                             "Profesional","Boca Juniors"
,"1993","Copa Centenario de la AFA 1993",	                                 "Profesional","Gimnasia y Esgrima de La Plata"
,"2012","Copa Argentina 2012",	                                             "Profesional","Boca Juniors"
,"2012","Supercopa Argentina 2012",	                                         "Profesional","Arsenal Fútbol Club"
,"2013","Copa Argentina 2013",	                                             "Profesional","Arsenal Fútbol Club"
,"2013","Supercopa Argentina 2013",	                                         "Profesional","Vélez Sarsfield"
,"2013","Copa Campeonato Primera División 2013/2014",	                     "Profesional","River Plate"
,"2013","Copa Argentina 2013/2014",             	                         "Profesional","Huracán"
,"2014","Supercopa Argentina 2014",	                                         "Profesional","Huracán"
,"2014","Copa Argentina 2014/2015",	                                         "Profesional","Boca Juniors"
,"2015","Supercopa 2015",	                                                 "Profesional","San Lorenzo de Almagro"
,"2016","Copa Bicentenario 2016",	                                         "Profesional","Lanús"
,"2016","Copa Argentina 2015/2016",	                                         "Profesional","River Plate"
,"2016","Supercopa 2016",	                                                 "Profesional","Lanús"
,"2017","Copa Argentina 2017",	                                             "Profesional","River Plate"
,"2017","Supercopa Argentina 2017",	                                         "Profesional","River Plate"
,"2017","Copa Argentina 2017/2018",                                          "Profesional","Rosario Central"
,"2018","Supercopa Argentina 2018" ,                                         "Profesional","Boca Juniors"
,"2019","Copa de la Superliga 2019",                                         "Profesional","Tigre"
,"2019","Copa Argentina 2019",	                                             "Profesional","River Plate"
,"2019","Trofeo de Campeones de la Superliga 2019",	                         "Profesional","Racing Club"
,"2020","Copa Diego Armando Maradona 2020 - 2021", 	                         "Profesional","Boca Juniors"
,"2019","Supercopa Argentina 2019",                                          "Profesional","River Plate"
,"2021","Copa de la Liga Profesional  2021",                                 "Profesional","Club Atlético Colón"
,"2020","Copa Argentina 2020",	                                             "Profesional","Boca Juniors"
,"2021","Trofeo de Campeones 2021",	                                         "Profesional","River Plate"
,"2022", "Trofeo de Campeones 2022",                                         "Profesional", "Racing Club"
]