tabla_ligas = [
"1891","Liga",	                                                           "Amateur","Saint Andrews"
,"1892","Liga",	                                                           "Amateur","(No hubo torneo)"
,"1893","Liga",	                                                           "Amateur","Lomas Athletic"
,"1894","Liga",	                                                           "Amateur","Lomas Athletic"
,"1895","Liga",	                                                           "Amateur","Lomas Athletic"
,"1896","Liga",	                                                           "Amateur","Lomas Academy"
,"1897","Liga",	                                                           "Amateur","Lomas Athletic"
,"1898","Liga",	                                                           "Amateur","Lomas Athletic"
,"1899","Liga",	                                                           "Amateur","Belgrano Athletic"
,"1900","Liga",	                                                           "Amateur","English High School"
,"1901","Liga",	                                                           "Amateur","Alumni"
,"1902","Liga",	                                                           "Amateur","Alumni"
,"1903","Liga",	                                                           "Amateur","Alumni"
,"1904","Liga",	                                                           "Amateur","Belgrano Athletic"
,"1905","Liga",	                                                           "Amateur","Alumni"
,"1906","Liga",	                                                           "Amateur","Alumni"
,"1907","Liga",	                                                           "Amateur","Alumni"
,"1908","Liga",	                                                           "Amateur","Belgrano Athletic"
,"1909","Liga",	                                                           "Amateur","Alumni"
,"1910","Liga",	                                                           "Amateur","Alumni"
,"1911","Liga",	                                                           "Amateur","Alumni"
,"1912", "Asociación Argentina de Football",                               "Amateur","Quilmes"
,"1912", "Federación Argentina de Football",                               "Amateur","Porteño"
,"1913", "Asociación Argentina de Football",                               "Amateur","Racing Club"
,"1913", "Federación Argentina de Football",                               "Amateur","Estudiantes de La Plata"
,"1914", "Asociación Argentina de Football",                               "Amateur","Racing Club"
,"1914", "Federación Argentina de Football",                               "Amateur","Porteño"
,"1915","Liga",                                                            "Amateur","Racing Club"
,"1916","Liga",                                                            "Amateur","Racing Club"
,"1917","Liga",                                                            "Amateur","Racing Club"
,"1918","Liga",                                                            "Amateur","Racing Club"
,"1919", "Asociación Argentina de Football",	                           "Amateur","Boca Juniors"
,"1919", "Asociación Amateur Argentina de Football"	,                      "Amateur","Racing Club"
,"1920", "Asociación Argentina de Football",                               "Amateur","Boca Juniors"
,"1920", "Asociación Amateur Argentina de Football",                       "Amateur","River Plate"
,"1921", "Asociación Argentina de Football",                               "Amateur","Huracán"
,"1921", "Asociación Amateur Argentina de Football",                       "Amateur","Racing Club"
,"1922", "Asociación Argentina de Football",                               "Amateur","Huracán"
,"1922", "Asociación Amateur Argentina de Football",                       "Amateur","Independiente"
,"1923", "Asociación Argentina de Football",                               "Amateur","Boca Juniors"
,"1923", "Asociación Amateur Argentina de Football",                       "Amateur","San Lorenzo de Almagro"
,"1924", "Asociación Argentina de Football",                               "Amateur","Boca Juniors"
,"1924", "Asociación Amateur Argentina de Football",                       "Amateur","San Lorenzo de Almagro"
,"1925", "Asociación Argentina de Football",                               "Amateur","Huracán"
,"1925", "Asociación Amateur Argentina de Football",                       "Amateur","Racing Club"
,"1926", "Asociación Argentina de Football",                               "Amateur","Boca Juniors"
,"1926", "Asociación Amateur Argentina de Football",                       "Amateur","Independiente"
,"1927",	"Liga",                                                        "Amateur","San Lorenzo de Almagro"
,"1928",	"Liga",                                                        "Amateur","Huracán"
,"1929",	"Liga",                                                        "Amateur","Gimnasia y Esgrima La Plata"
,"1930",	"Liga",                                                        "Amateur","Boca Juniors"
,"1931", "Asociación Argentina de Football",                               "Amateur","Estudiantil Porteño"
,"1932", "Asociación Argentina de Football",                               "Amateur","Sportivo Barracas"
,"1933", "Asociación Argentina de Football",                               "Amateur","Dock Sud"
,"1934", "Asociación Argentina de Football",                               "Amateur","Estudiantil Porteño"
,"1931" ,"Liga Argentina de Football",	                                   "Profesional","Boca Juniors"
,"1932" ,"Liga Argentina de Football",	                                   "Profesional","River Plate"
,"1933" ,"Liga Argentina de Football",	                                   "Profesional","San Lorenzo de Almagro"
,"1934" ,"Liga Argentina de Football",	                                   "Profesional","Boca Juniors"
,"1935"	,"Liga",                                                           "Profesional","Boca Juniors"
,"1936" ,"Copa de Honor"	,                                              "Profesional","San Lorenzo de Almagro"
,"1936" ,"Copa Campeonato"	,                                              "Profesional","River Plate"
,"1936" ,"Copa de Oro"	,                                                  "Profesional","River Plate"
,"1937", "Liga",	                                                       "Profesional","River Plate"
,"1938", "Liga",	                                                       "Profesional","Independiente"
,"1939", "Liga",	                                                       "Profesional","Independiente"
,"1940", "Liga",	                                                       "Profesional","Boca Juniors"
,"1941", "Liga",	                                                       "Profesional","River Plate"
,"1942", "Liga",	                                                       "Profesional","River Plate"
,"1943", "Liga",	                                                       "Profesional","Boca Juniors"
,"1944", "Liga",	                                                       "Profesional","Boca Juniors"
,"1945", "Liga",	                                                       "Profesional","River Plate"
,"1946", "Liga",	                                                       "Profesional","San Lorenzo de Almagro"
,"1947", "Liga",	                                                       "Profesional","River Plate"
,"1948", "Liga",	                                                       "Profesional","Independiente"
,"1949", "Liga",	                                                       "Profesional","Racing Club"
,"1950", "Liga",	                                                       "Profesional","Racing Club"
,"1951", "Liga",	                                                       "Profesional","Racing Club"
,"1952", "Liga",	                                                       "Profesional","River Plate"
,"1953", "Liga",	                                                       "Profesional","River Plate"
,"1954", "Liga",	                                                       "Profesional","Boca Juniors"
,"1955", "Liga",	                                                       "Profesional","River Plate"
,"1956", "Liga",	                                                       "Profesional","River Plate"
,"1957", "Liga",	                                                       "Profesional","River Plate"
,"1958", "Liga",	                                                       "Profesional","Racing Club"
,"1959", "Liga",	                                                       "Profesional","San Lorenzo de Almagro"
,"1960", "Liga",	                                                       "Profesional","Independiente"
,"1961", "Liga",	                                                       "Profesional","Racing Club"
,"1962", "Liga",	                                                       "Profesional","Boca Juniors"
,"1963", "Liga",	                                                       "Profesional","Independiente"
,"1964", "Liga",	                                                       "Profesional","Boca Juniors"
,"1965", "Liga",	                                                       "Profesional","Boca Juniors"
,"1966", "Liga",	                                                       "Profesional","Racing Club"
,"1967" ,"(Metropolitano)",	                                               "Profesional","Estudiantes de La Plata"
,"1967" ,"(Nacional)",                                                     "Profesional","Independiente"
,"1968" ,"(Metropolitano)",                                                "Profesional","San Lorenzo de Almagro"
,"1968" ,"(Nacional)",                                                     "Profesional","Vélez Sarsfield"
,"1969" ,"(Metropolitano)",                                                "Profesional","Chacarita Juniors"
,"1969" ,"(Nacional)",                                                     "Profesional","Boca Juniors"
,"1970" ,"(Metropolitano)",                                                "Profesional","Independiente"
,"1970" ,"(Nacional)",                                                     "Profesional","Boca Juniors"
,"1971" ,"(Metropolitano)",                                                "Profesional","Independiente"
,"1971" ,"(Nacional)",                                                     "Profesional","Rosario Central"
,"1972" ,"(Metropolitano)",                                                "Profesional","San Lorenzo de Almagro"
,"1972" ,"(Nacional)"	,                                                  "Profesional","San Lorenzo de Almagro"
,"1973" ,"(Metropolitano)"	,                                              "Profesional","Huracán"
,"1973" ,"(Nacional)"	,                                                  "Profesional","Rosario Central"
,"1974" ,"(Metropolitano)"	,                                              "Profesional","Newells Old Boys"
,"1974" ,"(Nacional)"	,                                                  "Profesional","San Lorenzo de Almagro"
,"1975" ,"(Metropolitano)"	,                                              "Profesional","River Plate"
,"1975" ,"(Nacional)"	,                                                  "Profesional","River  Plate"
,"1976" ,"(Metropolitano)"	,                                              "Profesional","Boca Juniors"
,"1976" ,"(Nacional)"	,                                                  "Profesional","Boca Juniors"
,"1977" ,"(Metropolitano)"	,                                              "Profesional","River Plate"
,"1977" ,"(Nacional)"	,                                                  "Profesional","Independiente"
,"1978" ,"(Metropolitano)"	,                                              "Profesional","Quilmes"
,"1978" ,"(Nacional)"	,                                                  "Profesional","Independiente"
,"1979" ,"(Metropolitano)",	                                               "Profesional","River Plate"
,"1979" ,"(Nacional)"	,                                                  "Profesional","River Plate"
,"1980" ,"(Metropolitano)",	                                               "Profesional","River Plate"
,"1980" ,"(Nacional)"	,                                                  "Profesional","Rosario Central"
,"1981" ,"(Metropolitano)",	                                               "Profesional","Boca Juniors"
,"1981" ,"(Nacional)"	,                                                  "Profesional","River Plate"
,"1982" ,"(Metropolitano)"	,                                              "Profesional","Estudiantes de La Plata"
,"1982" ,"(Nacional)"	,                                                  "Profesional","Ferro Carril Oeste"
,"1983" ,"(Metropolitano)"	,                                              "Profesional","Independiente"
,"1983" ,"(Nacional)"	,                                                  "Profesional","Estudiantes de La Plata"
,"1984" ,"(Metropolitano)",                                                "Profesional","Argentinos Juniors"
,"1984" ,"(Nacional)"	,                                                  "Profesional","Ferro Carril Oeste"
,"1985" ,"(Nacional)"	,                                                  "Profesional","Argentinos Juniors"
,"1986","Liga",	                                                           "Profesional","River Plate"
,"1987","Liga",	                                                           "Profesional","Rosario Central"
,"1988","Liga",	                                                           "Profesional","Newells Old Boys"
,"1989","Liga",	                                                           "Profesional","Independiente"
,"1990","Liga",	                                                           "Profesional","River Plate"
,"1991","Liga",	                                                           "Profesional","Newells Old Boys"
,"1991","Apertura",                                                        "Profesional","River Plate"
,"1992","Clausura",                                                        "Profesional","Newells Old Boys"
,"1992","Apertura",                                                        "Profesional","Boca Juniors"
,"1993","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"1993","Apertura",                                                        "Profesional","River Plate"
,"1994","Clausura",                                                        "Profesional","Independiente"
,"1994","Apertura",                                                        "Profesional","River Plate"
,"1995","Clausura",                                                        "Profesional","San Lorenzo de Almagro"
,"1995","Apertura",                                                        "Profesional","Vélez Sarsfield"
,"1996","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"1996","Apertura",                                                        "Profesional","River Plate"
,"1997","Clausura",                                                        "Profesional","River Plate"
,"1997","Apertura",                                                        "Profesional","River Plate"
,"1998","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"1998","Apertura",                                                        "Profesional","Boca Juniors"
,"1999","Clausura",                                                        "Profesional","Boca Juniors"
,"1999","Apertura",                                                        "Profesional","River Plate"
,"2000","Clausura",                                                        "Profesional","River Plate"
,"2000","Apertura",                                                        "Profesional","Boca Juniors"
,"2001","Clausura",                                                        "Profesional","San Lorenzo de Almagro"
,"2001","Apertura",                                                        "Profesional","Racing Club"
,"2002","Clausura",                                                        "Profesional","River Plate"
,"2002","Apertura",                                                        "Profesional","Independiente"
,"2003","Clausura",                                                        "Profesional","River Plate"
,"2003","Apertura",                                                        "Profesional","Boca Juniors"
,"2004","Clausura",                                                        "Profesional","River Plate"
,"2004","Apertura",                                                        "Profesional","Newells Old Boys"
,"2005","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"2005","Apertura",                                                        "Profesional","Boca Juniors"
,"2006","Clausura",                                                        "Profesional","Boca Juniors"
,"2006","Apertura",                                                        "Profesional","Estudiantes de La Plata"
,"2007","Clausura",                                                        "Profesional","San Lorenzo de Almagro"
,"2007","Apertura",                                                        "Profesional","Lanús"
,"2008","Clausura",                                                        "Profesional","River Plate"
,"2008","Apertura",                                                        "Profesional","Boca Juniors"
,"2009","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"2009","Apertura",                                                        "Profesional","Bánfield"
,"2010","Clausura",                                                        "Profesional","Argentinos Juniors"
,"2010","Apertura",                                                        "Profesional","Estudiantes de La Plata"
,"2011","Clausura",                                                        "Profesional","Vélez Sarsfield"
,"2011","Apertura",                                                        "Profesional","Boca Juniors"
,"2012","Clausura",                                                        "Profesional","Arsenal F.C."
,"2012","Torneo Inicial"	,                                              "Profesional","Vélez Sarsfield"
,"2013","Torneo Final",	                                                   "Profesional","Newells Old Boys"
,"2013","Campeón de Primera División 2012/13"	,                          "Profesional","Vélez Sarsfield"
,"2013","Torno Inicial"	,                                                  "Profesional","San Lorenzo de Almagro"
,"2014","Torneo Final",	                                                   "Profesional","River Plate"
,"2014","Torneo Inicial"	,                                              "Profesional","Racing Club"
,"2015","Campeonato de Primera División",	                               "Profesional","Boca Juniors"
,"2016","Campeonato de Primera División",	                               "Profesional","Lanús"
,"2018", "Superliga",                                                      "Profesional","Boca Juniors"
,"2019", "Superliga",                                                      "Profesional","Racing Club"
,"2020", "Superliga",                                                      "Profesional","Boca Juniors"
,"2021", "Torneo Socios de la Liga Profesional",                           "Profesional","River Plate"
,"2022", "Torneo Binance",                                                 "Profesional", "Boca Juniors"]